---
- name: this play book install httpd
  hosts: webservers
  become: true
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed

  - name: start httpd service
    service:
      name: httpd
      state: started
